/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 1.2 */
/* Thu May 27 12:36:38 2021 */

/* parameterized module instance */
EFB_Timer __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .tc_clki( ), .tc_rstn( ), .tc_ic( ), .tc_int( ), .tc_oc( ));
