/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Sun May 30 16:07:20 2021 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ));
